# Generated by Django 4.2.4 on 2023-08-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
