# Generated by Django 4.2.4 on 2023-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sex',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
